=== JoaoNunoAbreu/uminho-miei/4-Ano/1Semestre/DAW/tpcs/T3/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT pr (info,workteam,abstract, deliverables, date) >

<!-- INFO -->

<!ELEMENT info (key_name, title, subtitle?, begin_date, end_date, supervisor) >

<!ELEMENT key_name (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT begin_date (#PCDATA) >
<!ELEMENT end_date (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >

<!-- WORKTEAM -->

<!ELEMENT workteam (element)+ >

<!ELEMENT element (name,id_number,email,git_link) >

<!ELEMENT name (#PCDATA) >
<!ELEMENT id_number (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT git_link (#PCDATA) >

<!-- ABSTRACT -->

<!ELEMENT abstract (words)* >
<!ELEMENT words (#PCDATA|bold|italic|underline|link)* >
<!ELEMENT bold (#PCDATA|italic|underline|link)* >
<!ELEMENT italic (#PCDATA|bold|underline|link)* >
<!ELEMENT underline (#PCDATA|bold|italic|link)* >
<!ELEMENT link (#PCDATA) >

<!-- DELIVERABLES -->

<!ELEMENT deliverables (deliverable)* >
<!ELEMENT deliverable (#PCDATA)>

<!-- DATE -->

<!ELEMENT date (#PCDATA) >


<!-- ATTRIBUTES -->
<!ATTLIST supervisor url CDATA #REQUIRED >       
<!ATTLIST deliverable url CDATA #REQUIRED>
<!ATTLIST git_link url CDATA #REQUIRED>
<!ATTLIST link url CDATA #REQUIRED>

=== JoaoNunoAbreu/uminho-miei/4-Ano/1Semestre/DAW/tpcs/T2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "pr.dtd">
<pr>
    <info>
        <key_name>Project Record</key_name>
        <title>TPC3 DAW 2020</title>
        <subtitle>DTD e XML</subtitle>
        <begin_date>Outubro 2020</begin_date>
        <end_date>Outubro 2020</end_date>
        <supervisor url="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </info>
    <workteam>
        <element>
            <name>João Nuno Abreu</name>
            <id_number>84802</id_number>
            <email>a84802@alunos.uminho.pt</email>
            <git_link url="https://github.com/joaonunoabreu/">GitHub</git_link>
        </element>
    </workteam>
    <abstract>
        <words>O XML, validado pelo schema, juntamente com o potente processamento via XSLT, permite dispor de <italic>facilidades acrescidas</italic> no tratamento de informação de uma forma <bold>standard e partilhável</bold>. Estas são, além de outras evidentes vantagens, as que abrem caminho a uma mais que provável evolução desta tecnologia nos círculos comerciais e de investigação. Outro facto importante, diz respeito à substituição de interfaces EDI por XML em aplicações bussiness oriented.</words>
        <words>O trabalho apresentado contempla um <bold>schema, uma stylesheet, e a instância do schema</bold> em XML. A instância é o próprio relatório.</words>
        <words>O trabalho pretende definir uma <italic>estrutura expedita e funcional</italic>, passível de ser aplicada a um trabalho descritivo, como por exemplo uma tese. Não é objectivo do trabalho criar uma implementação sistemática de todos os objectos possíveis, mas sim criar algumas utilizações mais comuns para exemplificar a potência destas linguagens.</words>
        <words>Ficam neste trabalho em aberto algumas ideias, a serem aplicadas mais tarde a quando da escrita da tese, ou pré-tese, porque na verdade o facto de manter o documento num formato exportável para vários formatos, para várias plataformas, e anotado, garante qualquer tratamento no futuro, constituindo uma vantagem muito importante a ter em conta. </words>
        <words>Exemplo de link no parágrafo <link url="https://google.com"></link></words>
    </abstract>
    <deliverables>
        <deliverable url="./pr.xml">XML do project record</deliverable>
        <deliverable url="./pr.xsl">XSL do project record</deliverable>
        <deliverable url="./pr.html">HTML do project record</deliverable>
        <deliverable url="./pr.dtd">Ficheiro DTD do PR</deliverable>
        <deliverable url="./arq.xml">XML dos arqueossitios</deliverable>
        <deliverable url="./arq.xsl">XSL dos arqueossitios </deliverable>
        <deliverable url="./site/index.html">indice dos arqueossitios</deliverable>
    </deliverables>
    <date>29-10-2020</date>
</pr>

=== JoaoNunoAbreu/uminho-miei/4-Ano/1Semestre/DAW/tpcs/T3/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "pr.dtd">
<pr>
    <info>
        <key_name>XSL</key_name>
        <title>Geração de Website com transformações XSL</title>
        <begin_date>28 de Outubro de 2020</begin_date>
        <end_date>4 de Novembro de 2020</end_date>
        <supervisor url="http://www4.di.uminho.pt/~jcr/">José Carlos Ramalho</supervisor>
    </info>
    <workteam>
        <element>
            <name>João Nuno Abreu</name>
            <id_number>84802</id_number>
            <email>a84802@alunos.uminho.pt</email>
            <git_link url="https://github.com/joaonunoabreu/">GitHub</git_link>
        </element>
    </workteam>
    <abstract>
        <words>Neste projeto o principal objetivo foi a <bold>geração de um website com transformações XSL</bold> a partir de um dataset em XML, tendo uma página principal com o índice geral, e uma página individual para cada registo.</words> 
        <words> Foi tido me conta a existência de campos vazios para que não fossem exibidas opções em branco na página do registo. Foi também estudada a possibilidade de ter a opção de avançar para páginas seguintes, embora sem sucesso.</words>
    </abstract>
    <deliverables>
        <deliverable url="arq.xsl">Ficheiro XSL</deliverable>
        <deliverable url="arq.dtd">Ficheiro DTD</deliverable>
        <deliverable url="site/index.html">Ficheiro HTML</deliverable>
    </deliverables>
    <date>29-10-2020</date>
</pr>
